// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGA.Infrastructure.Data;

#nullable disable

namespace SGA.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGA.Domain.Entities.Docente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioNivelActual")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNombramiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaImportacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAscenso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasCapacitacion")
                        .HasColumnType("int");

                    b.Property<int?>("MesesInvestigacion")
                        .HasColumnType("int");

                    b.Property<string>("NivelActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NumeroObrasAcademicas")
                        .HasColumnType("int");

                    b.Property<decimal?>("PromedioEvaluaciones")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Docentes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2f3111eb-1567-48f9-a438-d90493df25f1"),
                            Apellidos = "Sistema",
                            Cedula = "1800000000",
                            Email = "admin@uta.edu.ec",
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 6, 25, 21, 26, 12, 45, DateTimeKind.Utc).AddTicks(6624),
                            FechaInicioNivelActual = new DateTime(2020, 6, 25, 21, 26, 12, 45, DateTimeKind.Utc).AddTicks(6273),
                            NivelActual = "Titular5",
                            Nombres = "Administrador",
                            UsuarioId = new Guid("6fa6dce8-66df-465c-a79c-0f6e2d2651c1")
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ContenidoArchivo")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SolicitudAscensoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TamanoArchivo")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudAscensoId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("SGA.Domain.Entities.LogAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DireccionIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("EntidadAfectada")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaAccion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("SGA.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AprobadoPorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasCapacitacion")
                        .HasColumnType("int");

                    b.Property<int>("MesesInvestigacion")
                        .HasColumnType("int");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelSolicitado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroObrasAcademicas")
                        .HasColumnType("int");

                    b.Property<decimal>("PromedioEvaluaciones")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TiempoEnNivelDias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AprobadoPorId");

                    b.HasIndex("DocenteId");

                    b.ToTable("SolicitudesAscenso");
                });

            modelBuilder.Entity("SGA.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntentosLogin")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoBloqueado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UltimoLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6fa6dce8-66df-465c-a79c-0f6e2d2651c1"),
                            Email = "admin@uta.edu.ec",
                            EstaActivo = true,
                            FechaCreacion = new DateTime(2025, 6, 25, 21, 26, 12, 45, DateTimeKind.Utc).AddTicks(621),
                            IntentosLogin = 0,
                            PasswordHash = "$2a$11$eWDAhgGAMRNpUkpUHlnwaefg3uyYXXV8CUkLZU76AaiP1bFNcUZuC",
                            Rol = "Administrador",
                            UltimoLogin = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.Docente", b =>
                {
                    b.HasOne("SGA.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Docente")
                        .HasForeignKey("SGA.Domain.Entities.Docente", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SGA.Domain.Entities.Documento", b =>
                {
                    b.HasOne("SGA.Domain.Entities.SolicitudAscenso", "SolicitudAscenso")
                        .WithMany("Documentos")
                        .HasForeignKey("SolicitudAscensoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudAscenso");
                });

            modelBuilder.Entity("SGA.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.HasOne("SGA.Domain.Entities.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("AprobadoPorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SGA.Domain.Entities.Docente", "Docente")
                        .WithMany("SolicitudesAscenso")
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AprobadoPor");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("SGA.Domain.Entities.Docente", b =>
                {
                    b.Navigation("SolicitudesAscenso");
                });

            modelBuilder.Entity("SGA.Domain.Entities.SolicitudAscenso", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("SGA.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Docente");
                });
#pragma warning restore 612, 618
        }
    }
}
