// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGA.Infrastructure.Data.External;

#nullable disable

namespace SGA.Infrastructure.Migrations.DIRINV
{
    [DbContext(typeof(DIRINVDbContext))]
    [Migration("20250627193927_CreateObrasAcademicasTable")]
    partial class CreateObrasAcademicasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGA.Domain.Entities.External.ObraAcademicaDIRINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editorial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EsIndexada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN_ISSN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndiceIndexacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Revista")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoObra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.ToTable("ObrasAcademicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "1800000001",
                            Editorial = "Editorial 4",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 12, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(7707),
                            ISBN_ISSN = "ISSN-5800-6989",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 1"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "1800000001",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 7, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8432),
                            ISBN_ISSN = "ISSN-6335-6781",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 1"
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "1800000001",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 10, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8442),
                            ISBN_ISSN = "ISSN-2533-7872",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 3 del Docente 1"
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "1800000002",
                            Editorial = "Editorial 1",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 5, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8449),
                            ISBN_ISSN = "ISSN-8138-6098",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 2"
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "1800000003",
                            Editorial = "Editorial 4",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 7, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8454),
                            ISBN_ISSN = "ISSN-7319-8302",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 3"
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "1800000003",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 8, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8461),
                            ISBN_ISSN = "ISSN-3468-8345",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 2 del Docente 3"
                        },
                        new
                        {
                            Id = 7,
                            Cedula = "1800000003",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 3, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8466),
                            ISBN_ISSN = "ISSN-3910-3074",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 3 del Docente 3"
                        },
                        new
                        {
                            Id = 8,
                            Cedula = "1800000003",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8481),
                            ISBN_ISSN = "ISSN-9689-5881",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 4 del Docente 3"
                        },
                        new
                        {
                            Id = 9,
                            Cedula = "1800000003",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 7, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8485),
                            ISBN_ISSN = "ISSN-3285-4103",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 5 del Docente 3"
                        },
                        new
                        {
                            Id = 10,
                            Cedula = "1800000004",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 3, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8489),
                            ISBN_ISSN = "ISSN-8757-4752",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 4"
                        },
                        new
                        {
                            Id = 11,
                            Cedula = "1800000004",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2020, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8493),
                            ISBN_ISSN = "ISSN-9305-7254",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 2 del Docente 4"
                        },
                        new
                        {
                            Id = 12,
                            Cedula = "1800000004",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 3, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8497),
                            ISBN_ISSN = "ISSN-9632-2053",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 4",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 4"
                        },
                        new
                        {
                            Id = 13,
                            Cedula = "1800000006",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 1, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8501),
                            ISBN_ISSN = "ISSN-8769-9632",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 6"
                        },
                        new
                        {
                            Id = 14,
                            Cedula = "1800000006",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8504),
                            ISBN_ISSN = "ISSN-7132-7005",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 6"
                        },
                        new
                        {
                            Id = 15,
                            Cedula = "1800000008",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8508),
                            ISBN_ISSN = "ISSN-2660-2862",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 8"
                        },
                        new
                        {
                            Id = 16,
                            Cedula = "1800000008",
                            Editorial = "Editorial 4",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2022, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8510),
                            ISBN_ISSN = "ISSN-1023-7832",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 8"
                        },
                        new
                        {
                            Id = 17,
                            Cedula = "1800000008",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8514),
                            ISBN_ISSN = "ISSN-8827-3697",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 3 del Docente 8"
                        },
                        new
                        {
                            Id = 18,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 2, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8519),
                            ISBN_ISSN = "ISSN-8593-3760",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 9"
                        },
                        new
                        {
                            Id = 19,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 12, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8522),
                            ISBN_ISSN = "ISSN-8800-8666",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 9"
                        },
                        new
                        {
                            Id = 20,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 6, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8525),
                            ISBN_ISSN = "ISSN-7477-9925",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 4",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 9"
                        },
                        new
                        {
                            Id = 21,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 3, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8528),
                            ISBN_ISSN = "ISSN-8134-4240",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 4 del Docente 9"
                        },
                        new
                        {
                            Id = 22,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 1, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8531),
                            ISBN_ISSN = "ISSN-2143-1538",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 5 del Docente 9"
                        },
                        new
                        {
                            Id = 23,
                            Cedula = "1800000011",
                            Editorial = "Editorial 2",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2022, 7, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8536),
                            ISBN_ISSN = "ISSN-5900-5784",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 11"
                        },
                        new
                        {
                            Id = 24,
                            Cedula = "1800000011",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 10, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8539),
                            ISBN_ISSN = "ISSN-1252-9250",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 2 del Docente 11"
                        },
                        new
                        {
                            Id = 25,
                            Cedula = "1800000011",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 10, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8542),
                            ISBN_ISSN = "ISSN-6998-1524",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 11"
                        },
                        new
                        {
                            Id = 26,
                            Cedula = "1800000011",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8546),
                            ISBN_ISSN = "ISSN-7495-6143",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 4 del Docente 11"
                        },
                        new
                        {
                            Id = 27,
                            Cedula = "1800000011",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 6, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8550),
                            ISBN_ISSN = "ISSN-9566-5298",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 5 del Docente 11"
                        },
                        new
                        {
                            Id = 28,
                            Cedula = "1800000012",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 7, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8554),
                            ISBN_ISSN = "ISSN-7947-7804",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 12"
                        },
                        new
                        {
                            Id = 29,
                            Cedula = "1800000012",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8557),
                            ISBN_ISSN = "ISSN-8403-2197",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 2 del Docente 12"
                        },
                        new
                        {
                            Id = 30,
                            Cedula = "1800000012",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8560),
                            ISBN_ISSN = "ISSN-5291-2736",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 12"
                        },
                        new
                        {
                            Id = 31,
                            Cedula = "1800000012",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 6, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8563),
                            ISBN_ISSN = "ISSN-1877-9085",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 4 del Docente 12"
                        },
                        new
                        {
                            Id = 32,
                            Cedula = "1800000014",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 2, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8576),
                            ISBN_ISSN = "ISSN-6968-9412",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 4",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 14"
                        },
                        new
                        {
                            Id = 33,
                            Cedula = "1800000014",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8580),
                            ISBN_ISSN = "ISSN-6702-1005",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 2 del Docente 14"
                        },
                        new
                        {
                            Id = 34,
                            Cedula = "1800000014",
                            Editorial = "Editorial 1",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 12, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8585),
                            ISBN_ISSN = "ISSN-2006-4103",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 3 del Docente 14"
                        },
                        new
                        {
                            Id = 35,
                            Cedula = "1800000014",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 6, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8588),
                            ISBN_ISSN = "ISSN-2199-5162",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 4 del Docente 14"
                        },
                        new
                        {
                            Id = 36,
                            Cedula = "1800000014",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8591),
                            ISBN_ISSN = "ISSN-3632-6404",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 5 del Docente 14"
                        },
                        new
                        {
                            Id = 37,
                            Cedula = "1800000015",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8595),
                            ISBN_ISSN = "ISSN-5579-4876",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 15"
                        },
                        new
                        {
                            Id = 38,
                            Cedula = "1800000015",
                            Editorial = "Editorial 4",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8598),
                            ISBN_ISSN = "ISSN-4796-9682",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 15"
                        },
                        new
                        {
                            Id = 39,
                            Cedula = "1800000015",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 10, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8602),
                            ISBN_ISSN = "ISSN-2630-9550",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 4",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 15"
                        },
                        new
                        {
                            Id = 40,
                            Cedula = "1800000016",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 8, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8605),
                            ISBN_ISSN = "ISSN-8017-1527",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 16"
                        },
                        new
                        {
                            Id = 41,
                            Cedula = "1800000016",
                            Editorial = "Editorial 2",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8608),
                            ISBN_ISSN = "ISSN-6627-8392",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 16"
                        },
                        new
                        {
                            Id = 42,
                            Cedula = "1800000016",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 8, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8611),
                            ISBN_ISSN = "ISSN-6603-8262",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 3 del Docente 16"
                        },
                        new
                        {
                            Id = 43,
                            Cedula = "1800000016",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 3, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8614),
                            ISBN_ISSN = "ISSN-2744-7354",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 4 del Docente 16"
                        },
                        new
                        {
                            Id = 44,
                            Cedula = "1800000016",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 11, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8617),
                            ISBN_ISSN = "ISSN-1457-8728",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 5 del Docente 16"
                        },
                        new
                        {
                            Id = 45,
                            Cedula = "1800000017",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8620),
                            ISBN_ISSN = "ISSN-8034-7226",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 17"
                        },
                        new
                        {
                            Id = 46,
                            Cedula = "1800000017",
                            Editorial = "Editorial 1",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 2, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8623),
                            ISBN_ISSN = "ISSN-5416-2445",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 17"
                        },
                        new
                        {
                            Id = 47,
                            Cedula = "1800000018",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8627),
                            ISBN_ISSN = "ISSN-4488-9342",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 18"
                        },
                        new
                        {
                            Id = 48,
                            Cedula = "1800000019",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 7, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8630),
                            ISBN_ISSN = "ISSN-1246-5637",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 19"
                        },
                        new
                        {
                            Id = 49,
                            Cedula = "1800000019",
                            Editorial = "Editorial 1",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2020, 9, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8633),
                            ISBN_ISSN = "ISSN-6703-8689",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 19"
                        },
                        new
                        {
                            Id = 50,
                            Cedula = "1800000019",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2022, 12, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8637),
                            ISBN_ISSN = "ISSN-6558-9157",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 3 del Docente 19"
                        },
                        new
                        {
                            Id = 51,
                            Cedula = "1800000019",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 6, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8640),
                            ISBN_ISSN = "ISSN-2485-5785",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 4 del Docente 19"
                        },
                        new
                        {
                            Id = 52,
                            Cedula = "1800000019",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 10, 27, 19, 39, 26, 757, DateTimeKind.Utc).AddTicks(8643),
                            ISBN_ISSN = "ISSN-4791-1005",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 5 del Docente 19"
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ParticipacionProyectoDIRINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RolEnProyecto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ParticipacionesProyecto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "1800000001",
                            FechaFin = new DateTime(2025, 9, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9817),
                            FechaInicio = new DateTime(2023, 10, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9817),
                            HorasSemanales = 11,
                            ProyectoId = 6,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "1800000002",
                            FechaFin = new DateTime(2026, 1, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            FechaInicio = new DateTime(2024, 6, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            HorasSemanales = 12,
                            ProyectoId = 1,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "1800000004",
                            FechaFin = new DateTime(2024, 7, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9810),
                            FechaInicio = new DateTime(2022, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9810),
                            HorasSemanales = 16,
                            ProyectoId = 5,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "1800000004",
                            FechaFin = new DateTime(2025, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            FechaInicio = new DateTime(2023, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            HorasSemanales = 13,
                            ProyectoId = 3,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "1800000005",
                            FechaFin = new DateTime(2026, 1, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            FechaInicio = new DateTime(2024, 6, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            HorasSemanales = 14,
                            ProyectoId = 1,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "1800000005",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            FechaInicio = new DateTime(2023, 12, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            HorasSemanales = 9,
                            ProyectoId = 8,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 7,
                            Cedula = "1800000007",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            FechaInicio = new DateTime(2023, 12, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            HorasSemanales = 17,
                            ProyectoId = 8,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 8,
                            Cedula = "1800000009",
                            FechaFin = new DateTime(2026, 1, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            FechaInicio = new DateTime(2024, 6, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            HorasSemanales = 15,
                            ProyectoId = 1,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 9,
                            Cedula = "1800000012",
                            FechaFin = new DateTime(2025, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            FechaInicio = new DateTime(2023, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            HorasSemanales = 15,
                            ProyectoId = 3,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 10,
                            Cedula = "1800000012",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9828),
                            FechaInicio = new DateTime(2022, 6, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9828),
                            HorasSemanales = 15,
                            ProyectoId = 10,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 11,
                            Cedula = "1800000013",
                            FechaFin = new DateTime(2024, 11, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9825),
                            FechaInicio = new DateTime(2022, 8, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9825),
                            HorasSemanales = 16,
                            ProyectoId = 9,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 12,
                            Cedula = "1800000013",
                            FechaFin = new DateTime(2024, 5, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9789),
                            FechaInicio = new DateTime(2022, 11, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9789),
                            HorasSemanales = 15,
                            ProyectoId = 2,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 13,
                            Cedula = "1800000014",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            FechaInicio = new DateTime(2023, 12, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            HorasSemanales = 12,
                            ProyectoId = 8,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 14,
                            Cedula = "1800000015",
                            FechaFin = new DateTime(2024, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9819),
                            FechaInicio = new DateTime(2022, 4, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9819),
                            HorasSemanales = 15,
                            ProyectoId = 7,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 15,
                            Cedula = "1800000015",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9807),
                            FechaInicio = new DateTime(2023, 8, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9807),
                            HorasSemanales = 5,
                            ProyectoId = 4,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 16,
                            Cedula = "1800000016",
                            FechaFin = new DateTime(2025, 9, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9817),
                            FechaInicio = new DateTime(2023, 10, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9817),
                            HorasSemanales = 14,
                            ProyectoId = 6,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 17,
                            Cedula = "1800000017",
                            FechaFin = new DateTime(2025, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            FechaInicio = new DateTime(2023, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            HorasSemanales = 18,
                            ProyectoId = 3,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 18,
                            Cedula = "1800000017",
                            FechaFin = new DateTime(2024, 11, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9825),
                            FechaInicio = new DateTime(2022, 8, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9825),
                            HorasSemanales = 8,
                            ProyectoId = 9,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 19,
                            Cedula = "1800000018",
                            FechaFin = new DateTime(2024, 7, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9810),
                            FechaInicio = new DateTime(2022, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9810),
                            HorasSemanales = 11,
                            ProyectoId = 5,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 20,
                            Cedula = "1800000020",
                            FechaFin = new DateTime(2025, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            FechaInicio = new DateTime(2023, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            HorasSemanales = 7,
                            ProyectoId = 3,
                            RolEnProyecto = "Investigador"
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ProyectoInvestigacionDIRINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuenteFinanciamiento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PresupuestoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ProyectosInvestigacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Descripción del proyecto de investigación número 1",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2026, 1, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            FechaInicio = new DateTime(2024, 6, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(7337),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 38029m,
                            Titulo = "Proyecto de Investigación 1"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Descripción del proyecto de investigación número 2",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2024, 5, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9789),
                            FechaInicio = new DateTime(2022, 11, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9789),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 24335m,
                            Titulo = "Proyecto de Investigación 2"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Descripción del proyecto de investigación número 3",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            FechaInicio = new DateTime(2023, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9804),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 45790m,
                            Titulo = "Proyecto de Investigación 3"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Descripción del proyecto de investigación número 4",
                            Estado = "Suspendido",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9807),
                            FechaInicio = new DateTime(2023, 8, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9807),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 18103m,
                            Titulo = "Proyecto de Investigación 4"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Descripción del proyecto de investigación número 5",
                            Estado = "En curso",
                            FechaFin = new DateTime(2024, 7, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9810),
                            FechaInicio = new DateTime(2022, 3, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9810),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 16816m,
                            Titulo = "Proyecto de Investigación 5"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Descripción del proyecto de investigación número 6",
                            Estado = "En curso",
                            FechaFin = new DateTime(2025, 9, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9817),
                            FechaInicio = new DateTime(2023, 10, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9817),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 22207m,
                            Titulo = "Proyecto de Investigación 6"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Descripción del proyecto de investigación número 7",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2024, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9819),
                            FechaInicio = new DateTime(2022, 4, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9819),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 47090m,
                            Titulo = "Proyecto de Investigación 7"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Descripción del proyecto de investigación número 8",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            FechaInicio = new DateTime(2023, 12, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9822),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 47270m,
                            Titulo = "Proyecto de Investigación 8"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Descripción del proyecto de investigación número 9",
                            Estado = "Suspendido",
                            FechaFin = new DateTime(2024, 11, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9825),
                            FechaInicio = new DateTime(2022, 8, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9825),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 48793m,
                            Titulo = "Proyecto de Investigación 9"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Descripción del proyecto de investigación número 10",
                            Estado = "En curso",
                            FechaFin = new DateTime(2025, 2, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9828),
                            FechaInicio = new DateTime(2022, 6, 27, 19, 39, 26, 756, DateTimeKind.Utc).AddTicks(9828),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 46657m,
                            Titulo = "Proyecto de Investigación 10"
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ParticipacionProyectoDIRINV", b =>
                {
                    b.HasOne("SGA.Domain.Entities.External.ProyectoInvestigacionDIRINV", "Proyecto")
                        .WithMany("Participaciones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ProyectoInvestigacionDIRINV", b =>
                {
                    b.Navigation("Participaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
