// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGA.Infrastructure.Data.External;

#nullable disable

namespace SGA.Infrastructure.Migrations.DIRINV
{
    [DbContext(typeof(DIRINVDbContext))]
    [Migration("20250627194007_UpdateDIRINVSchema")]
    partial class UpdateDIRINVSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGA.Domain.Entities.External.ObraAcademicaDIRINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DOI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Editorial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("EsIndexada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN_ISSN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IndiceIndexacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Revista")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TipoObra")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.ToTable("ObrasAcademicas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "1800000001",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(2853),
                            ISBN_ISSN = "ISSN-5589-8221",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 1"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "1800000001",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3489),
                            ISBN_ISSN = "ISSN-9021-4107",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 2 del Docente 1"
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "1800000001",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 10, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3498),
                            ISBN_ISSN = "ISSN-2358-4883",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 3 del Docente 1"
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "1800000002",
                            Editorial = "Editorial 3",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 7, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3503),
                            ISBN_ISSN = "ISSN-3457-2375",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 2"
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "1800000003",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 11, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3509),
                            ISBN_ISSN = "ISSN-2412-3998",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 3"
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "1800000004",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3516),
                            ISBN_ISSN = "ISSN-2186-1253",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 4"
                        },
                        new
                        {
                            Id = 7,
                            Cedula = "1800000004",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3519),
                            ISBN_ISSN = "ISSN-9390-9454",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 2 del Docente 4"
                        },
                        new
                        {
                            Id = 8,
                            Cedula = "1800000004",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3532),
                            ISBN_ISSN = "ISSN-8115-1156",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 3 del Docente 4"
                        },
                        new
                        {
                            Id = 9,
                            Cedula = "1800000005",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3535),
                            ISBN_ISSN = "ISSN-9970-7732",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 5"
                        },
                        new
                        {
                            Id = 10,
                            Cedula = "1800000005",
                            Editorial = "Editorial 1",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 11, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3539),
                            ISBN_ISSN = "ISSN-4832-6400",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 5"
                        },
                        new
                        {
                            Id = 11,
                            Cedula = "1800000005",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 11, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3543),
                            ISBN_ISSN = "ISSN-1339-8438",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 3 del Docente 5"
                        },
                        new
                        {
                            Id = 12,
                            Cedula = "1800000006",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 6, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3546),
                            ISBN_ISSN = "ISSN-3979-3213",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 6"
                        },
                        new
                        {
                            Id = 13,
                            Cedula = "1800000006",
                            Editorial = "Editorial 2",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 2, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3549),
                            ISBN_ISSN = "ISSN-1803-8686",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 6"
                        },
                        new
                        {
                            Id = 14,
                            Cedula = "1800000006",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 5, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3552),
                            ISBN_ISSN = "ISSN-5600-2632",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 3 del Docente 6"
                        },
                        new
                        {
                            Id = 15,
                            Cedula = "1800000006",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3555),
                            ISBN_ISSN = "ISSN-2086-9640",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 4 del Docente 6"
                        },
                        new
                        {
                            Id = 16,
                            Cedula = "1800000007",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3558),
                            ISBN_ISSN = "ISSN-9293-6727",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 7"
                        },
                        new
                        {
                            Id = 17,
                            Cedula = "1800000007",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 11, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3561),
                            ISBN_ISSN = "ISSN-5847-5243",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 2 del Docente 7"
                        },
                        new
                        {
                            Id = 18,
                            Cedula = "1800000007",
                            Editorial = "Editorial 3",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 3, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3566),
                            ISBN_ISSN = "ISSN-1257-5297",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 3 del Docente 7"
                        },
                        new
                        {
                            Id = 19,
                            Cedula = "1800000008",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3569),
                            ISBN_ISSN = "ISSN-5595-6972",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 8"
                        },
                        new
                        {
                            Id = 20,
                            Cedula = "1800000008",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 10, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3572),
                            ISBN_ISSN = "ISSN-8412-1726",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 2 del Docente 8"
                        },
                        new
                        {
                            Id = 21,
                            Cedula = "1800000009",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3575),
                            ISBN_ISSN = "ISSN-1509-7046",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 9"
                        },
                        new
                        {
                            Id = 22,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 12, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3577),
                            ISBN_ISSN = "ISSN-5987-8463",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 9"
                        },
                        new
                        {
                            Id = 23,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3580),
                            ISBN_ISSN = "ISSN-9677-6134",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 3 del Docente 9"
                        },
                        new
                        {
                            Id = 24,
                            Cedula = "1800000009",
                            Editorial = "Editorial 3",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3583),
                            ISBN_ISSN = "ISSN-6972-2886",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 4 del Docente 9"
                        },
                        new
                        {
                            Id = 25,
                            Cedula = "1800000009",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3586),
                            ISBN_ISSN = "ISSN-8307-5029",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 5 del Docente 9"
                        },
                        new
                        {
                            Id = 26,
                            Cedula = "1800000010",
                            Editorial = "Editorial 1",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 11, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3591),
                            ISBN_ISSN = "ISSN-7480-5291",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 10"
                        },
                        new
                        {
                            Id = 27,
                            Cedula = "1800000010",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 12, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3594),
                            ISBN_ISSN = "ISSN-5851-1266",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 2 del Docente 10"
                        },
                        new
                        {
                            Id = 28,
                            Cedula = "1800000010",
                            Editorial = "Editorial 3",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3597),
                            ISBN_ISSN = "ISSN-8044-9186",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 3 del Docente 10"
                        },
                        new
                        {
                            Id = 29,
                            Cedula = "1800000010",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3600),
                            ISBN_ISSN = "ISSN-5369-8706",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 4 del Docente 10"
                        },
                        new
                        {
                            Id = 30,
                            Cedula = "1800000011",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2021, 10, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3604),
                            ISBN_ISSN = "ISSN-1203-8287",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 11"
                        },
                        new
                        {
                            Id = 31,
                            Cedula = "1800000011",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 6, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3608),
                            ISBN_ISSN = "ISSN-4434-7020",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 11"
                        },
                        new
                        {
                            Id = 32,
                            Cedula = "1800000011",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 2, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3616),
                            ISBN_ISSN = "ISSN-7914-7479",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 3 del Docente 11"
                        },
                        new
                        {
                            Id = 33,
                            Cedula = "1800000011",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3619),
                            ISBN_ISSN = "ISSN-5471-1029",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 4 del Docente 11"
                        },
                        new
                        {
                            Id = 34,
                            Cedula = "1800000011",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 7, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3624),
                            ISBN_ISSN = "ISSN-1709-9341",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 4",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 5 del Docente 11"
                        },
                        new
                        {
                            Id = 35,
                            Cedula = "1800000013",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3628),
                            ISBN_ISSN = "ISSN-7715-4220",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 13"
                        },
                        new
                        {
                            Id = 36,
                            Cedula = "1800000013",
                            Editorial = "Editorial 2",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3631),
                            ISBN_ISSN = "ISSN-5424-8477",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 13"
                        },
                        new
                        {
                            Id = 37,
                            Cedula = "1800000015",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 6, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3634),
                            ISBN_ISSN = "ISSN-1725-7812",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 15"
                        },
                        new
                        {
                            Id = 38,
                            Cedula = "1800000015",
                            Editorial = "Editorial 3",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2024, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3637),
                            ISBN_ISSN = "ISSN-1693-8195",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 15"
                        },
                        new
                        {
                            Id = 39,
                            Cedula = "1800000015",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3641),
                            ISBN_ISSN = "ISSN-1584-1058",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 15"
                        },
                        new
                        {
                            Id = 40,
                            Cedula = "1800000015",
                            Editorial = "Editorial 4",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 2, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3644),
                            ISBN_ISSN = "ISSN-3817-6588",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 4 del Docente 15"
                        },
                        new
                        {
                            Id = 41,
                            Cedula = "1800000016",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3647),
                            ISBN_ISSN = "ISSN-8549-4594",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 1 del Docente 16"
                        },
                        new
                        {
                            Id = 42,
                            Cedula = "1800000016",
                            Editorial = "Editorial 2",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3650),
                            ISBN_ISSN = "ISSN-6226-2875",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 16"
                        },
                        new
                        {
                            Id = 43,
                            Cedula = "1800000016",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 6, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3654),
                            ISBN_ISSN = "ISSN-7657-1501",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 16"
                        },
                        new
                        {
                            Id = 44,
                            Cedula = "1800000017",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 12, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3657),
                            ISBN_ISSN = "ISSN-3940-8346",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 1 del Docente 17"
                        },
                        new
                        {
                            Id = 45,
                            Cedula = "1800000017",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2022, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3659),
                            ISBN_ISSN = "ISSN-4481-5668",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 17"
                        },
                        new
                        {
                            Id = 46,
                            Cedula = "1800000017",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 5, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3662),
                            ISBN_ISSN = "ISSN-2041-3230",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 1",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 17"
                        },
                        new
                        {
                            Id = 47,
                            Cedula = "1800000018",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3666),
                            ISBN_ISSN = "ISSN-7594-9629",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 1 del Docente 18"
                        },
                        new
                        {
                            Id = 48,
                            Cedula = "1800000018",
                            Editorial = "Editorial 1",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 4, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3668),
                            ISBN_ISSN = "ISSN-3225-7627",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 18"
                        },
                        new
                        {
                            Id = 49,
                            Cedula = "1800000018",
                            Editorial = "Editorial 2",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 7, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3672),
                            ISBN_ISSN = "ISSN-1725-2284",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 3 del Docente 18"
                        },
                        new
                        {
                            Id = 50,
                            Cedula = "1800000018",
                            Editorial = "Editorial 1",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 2, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3675),
                            ISBN_ISSN = "ISSN-5252-7949",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 4 del Docente 18"
                        },
                        new
                        {
                            Id = 51,
                            Cedula = "1800000018",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2022, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3678),
                            ISBN_ISSN = "ISSN-3198-1237",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 5 del Docente 18"
                        },
                        new
                        {
                            Id = 52,
                            Cedula = "1800000019",
                            Editorial = "Editorial 1",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2020, 7, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3680),
                            ISBN_ISSN = "ISSN-7220-1526",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 19"
                        },
                        new
                        {
                            Id = 53,
                            Cedula = "1800000019",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2023, 8, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3684),
                            ISBN_ISSN = "ISSN-7923-9684",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Capítulo",
                            Titulo = "Obra Académica 2 del Docente 19"
                        },
                        new
                        {
                            Id = 54,
                            Cedula = "1800000019",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 2, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3690),
                            ISBN_ISSN = "ISSN-7819-9778",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 4",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 19"
                        },
                        new
                        {
                            Id = 55,
                            Cedula = "1800000020",
                            Editorial = "Editorial 3",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2024, 12, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3695),
                            ISBN_ISSN = "ISSN-9756-3397",
                            IndiceIndexacion = "Scopus",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 1 del Docente 20"
                        },
                        new
                        {
                            Id = 56,
                            Cedula = "1800000020",
                            Editorial = "Editorial 3",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 1, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3698),
                            ISBN_ISSN = "ISSN-1992-3299",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Libro",
                            Titulo = "Obra Académica 2 del Docente 20"
                        },
                        new
                        {
                            Id = 57,
                            Cedula = "1800000020",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2022, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3701),
                            ISBN_ISSN = "ISSN-3873-8526",
                            IndiceIndexacion = "Scopus",
                            Revista = "Revista Científica 2",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 3 del Docente 20"
                        },
                        new
                        {
                            Id = 58,
                            Cedula = "1800000020",
                            EsIndexada = true,
                            FechaPublicacion = new DateTime(2023, 9, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3705),
                            ISBN_ISSN = "ISSN-6647-3575",
                            IndiceIndexacion = "Latindex",
                            Revista = "Revista Científica 3",
                            TipoObra = "Artículo",
                            Titulo = "Obra Académica 4 del Docente 20"
                        },
                        new
                        {
                            Id = 59,
                            Cedula = "1800000020",
                            EsIndexada = false,
                            FechaPublicacion = new DateTime(2021, 3, 27, 19, 40, 6, 650, DateTimeKind.Utc).AddTicks(3707),
                            ISBN_ISSN = "ISSN-5075-2943",
                            IndiceIndexacion = "Latindex",
                            TipoObra = "Ponencia",
                            Titulo = "Obra Académica 5 del Docente 20"
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ParticipacionProyectoDIRINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("RolEnProyecto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.HasIndex("ProyectoId");

                    b.ToTable("ParticipacionesProyecto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cedula = "1800000002",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            HorasSemanales = 6,
                            ProyectoId = 5,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 2,
                            Cedula = "1800000002",
                            FechaFin = new DateTime(2024, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            FechaInicio = new DateTime(2023, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            HorasSemanales = 9,
                            ProyectoId = 4,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 3,
                            Cedula = "1800000003",
                            FechaFin = new DateTime(2025, 3, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5760),
                            FechaInicio = new DateTime(2023, 4, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5760),
                            HorasSemanales = 11,
                            ProyectoId = 6,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 4,
                            Cedula = "1800000003",
                            FechaFin = new DateTime(2024, 6, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            FechaInicio = new DateTime(2022, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            HorasSemanales = 13,
                            ProyectoId = 7,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 5,
                            Cedula = "1800000004",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            FechaInicio = new DateTime(2021, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            HorasSemanales = 6,
                            ProyectoId = 8,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 6,
                            Cedula = "1800000004",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            HorasSemanales = 17,
                            ProyectoId = 5,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 7,
                            Cedula = "1800000005",
                            FechaFin = new DateTime(2024, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            FechaInicio = new DateTime(2023, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            HorasSemanales = 18,
                            ProyectoId = 4,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 8,
                            Cedula = "1800000005",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5653),
                            FechaInicio = new DateTime(2021, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5653),
                            HorasSemanales = 19,
                            ProyectoId = 3,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 9,
                            Cedula = "1800000006",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            HorasSemanales = 15,
                            ProyectoId = 5,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 10,
                            Cedula = "1800000007",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            HorasSemanales = 15,
                            ProyectoId = 5,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 11,
                            Cedula = "1800000007",
                            FechaFin = new DateTime(2024, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            FechaInicio = new DateTime(2023, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            HorasSemanales = 11,
                            ProyectoId = 4,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 12,
                            Cedula = "1800000009",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            FechaInicio = new DateTime(2021, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            HorasSemanales = 6,
                            ProyectoId = 8,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 13,
                            Cedula = "1800000009",
                            FechaFin = new DateTime(2025, 11, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5778),
                            FechaInicio = new DateTime(2024, 2, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5778),
                            HorasSemanales = 17,
                            ProyectoId = 10,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 14,
                            Cedula = "1800000010",
                            FechaFin = new DateTime(2025, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(3688),
                            FechaInicio = new DateTime(2023, 8, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(3688),
                            HorasSemanales = 19,
                            ProyectoId = 1,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 15,
                            Cedula = "1800000011",
                            FechaFin = new DateTime(2023, 3, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5645),
                            FechaInicio = new DateTime(2022, 1, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5645),
                            HorasSemanales = 18,
                            ProyectoId = 2,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 16,
                            Cedula = "1800000011",
                            FechaFin = new DateTime(2024, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            FechaInicio = new DateTime(2023, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            HorasSemanales = 6,
                            ProyectoId = 4,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 17,
                            Cedula = "1800000013",
                            FechaFin = new DateTime(2025, 8, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            FechaInicio = new DateTime(2022, 11, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            HorasSemanales = 17,
                            ProyectoId = 9,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 18,
                            Cedula = "1800000013",
                            FechaFin = new DateTime(2024, 6, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            FechaInicio = new DateTime(2022, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            HorasSemanales = 9,
                            ProyectoId = 7,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 19,
                            Cedula = "1800000014",
                            FechaFin = new DateTime(2025, 8, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            FechaInicio = new DateTime(2022, 11, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            HorasSemanales = 6,
                            ProyectoId = 9,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 20,
                            Cedula = "1800000015",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            HorasSemanales = 16,
                            ProyectoId = 5,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 21,
                            Cedula = "1800000016",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5653),
                            FechaInicio = new DateTime(2021, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5653),
                            HorasSemanales = 13,
                            ProyectoId = 3,
                            RolEnProyecto = "Investigador"
                        },
                        new
                        {
                            Id = 22,
                            Cedula = "1800000017",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            FechaInicio = new DateTime(2021, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            HorasSemanales = 5,
                            ProyectoId = 8,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 23,
                            Cedula = "1800000018",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            HorasSemanales = 12,
                            ProyectoId = 5,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 24,
                            Cedula = "1800000019",
                            FechaFin = new DateTime(2024, 6, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            FechaInicio = new DateTime(2022, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            HorasSemanales = 12,
                            ProyectoId = 7,
                            RolEnProyecto = "Colaborador"
                        },
                        new
                        {
                            Id = 25,
                            Cedula = "1800000020",
                            FechaFin = new DateTime(2025, 3, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5760),
                            FechaInicio = new DateTime(2023, 4, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5760),
                            HorasSemanales = 9,
                            ProyectoId = 6,
                            RolEnProyecto = "Director"
                        },
                        new
                        {
                            Id = 26,
                            Cedula = "1800000020",
                            FechaFin = new DateTime(2025, 8, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            FechaInicio = new DateTime(2022, 11, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            HorasSemanales = 5,
                            ProyectoId = 9,
                            RolEnProyecto = "Investigador"
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ProyectoInvestigacionDIRINV", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuenteFinanciamiento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("PresupuestoTotal")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("ProyectosInvestigacion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Descripción del proyecto de investigación número 1",
                            Estado = "Suspendido",
                            FechaFin = new DateTime(2025, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(3688),
                            FechaInicio = new DateTime(2023, 8, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(3688),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 10115m,
                            Titulo = "Proyecto de Investigación 1"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Descripción del proyecto de investigación número 2",
                            Estado = "En curso",
                            FechaFin = new DateTime(2023, 3, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5645),
                            FechaInicio = new DateTime(2022, 1, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5645),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 17655m,
                            Titulo = "Proyecto de Investigación 2"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Descripción del proyecto de investigación número 3",
                            Estado = "En curso",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5653),
                            FechaInicio = new DateTime(2021, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5653),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 42815m,
                            Titulo = "Proyecto de Investigación 3"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Descripción del proyecto de investigación número 4",
                            Estado = "Suspendido",
                            FechaFin = new DateTime(2024, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            FechaInicio = new DateTime(2023, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5657),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 47794m,
                            Titulo = "Proyecto de Investigación 4"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Descripción del proyecto de investigación número 5",
                            Estado = "En curso",
                            FechaFin = new DateTime(2023, 12, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FechaInicio = new DateTime(2022, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5661),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 20696m,
                            Titulo = "Proyecto de Investigación 5"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Descripción del proyecto de investigación número 6",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 3, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5760),
                            FechaInicio = new DateTime(2023, 4, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5760),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 30505m,
                            Titulo = "Proyecto de Investigación 6"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Descripción del proyecto de investigación número 7",
                            Estado = "Suspendido",
                            FechaFin = new DateTime(2024, 6, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            FechaInicio = new DateTime(2022, 7, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5769),
                            FuenteFinanciamiento = "Externo",
                            PresupuestoTotal = 44733m,
                            Titulo = "Proyecto de Investigación 7"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Descripción del proyecto de investigación número 8",
                            Estado = "Suspendido",
                            FechaFin = new DateTime(2023, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            FechaInicio = new DateTime(2021, 10, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5772),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 20629m,
                            Titulo = "Proyecto de Investigación 8"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Descripción del proyecto de investigación número 9",
                            Estado = "Finalizado",
                            FechaFin = new DateTime(2025, 8, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            FechaInicio = new DateTime(2022, 11, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5774),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 24496m,
                            Titulo = "Proyecto de Investigación 9"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Descripción del proyecto de investigación número 10",
                            Estado = "En curso",
                            FechaFin = new DateTime(2025, 11, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5778),
                            FechaInicio = new DateTime(2024, 2, 27, 19, 40, 6, 649, DateTimeKind.Utc).AddTicks(5778),
                            FuenteFinanciamiento = "Universidad",
                            PresupuestoTotal = 11584m,
                            Titulo = "Proyecto de Investigación 10"
                        });
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ParticipacionProyectoDIRINV", b =>
                {
                    b.HasOne("SGA.Domain.Entities.External.ProyectoInvestigacionDIRINV", "Proyecto")
                        .WithMany("Participaciones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("SGA.Domain.Entities.External.ProyectoInvestigacionDIRINV", b =>
                {
                    b.Navigation("Participaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
